backend/cmsacc/urls.py
from django.urls import path
from . import views

app_name = 'cmsacc'
urlpatterns = [
    path('payments/today', views.PaymentsToday.as_view(), name='PaymentToday'),
    ]

backend/cmsinv/urls.py
from django.urls import path
from . import views

app_name = 'cmsinv'
urlpatterns = [
    path('delivery/new/fromorder/<int:delivery_id>/modal/', views.NewDeliveryFromDeliveryOrderModalView, name='NewDeliveryFromDeliveryOrderModal'),
    path('suppliers/', views.SupplierList.as_view(), name='SupplierList'),
    path('supplier/<int:pk>/quickedit/modal/', views.SupplierQuickEditModal.as_view(), name='SupplierQuickEditModal'),
    # path('item/match/delivery/<int:delivery_id>/', views.MatchDeliveryInventoryItemList.as_view(), name='MatchDeliveryInventoryItemList'), # Non-CMS Delivery
    # path('item/match/<str:reg_no>/', views.MatchInventoryItemList.as_view(), name='MatchInventoryItemList'),
    # path('item/match/<int:pk>/update/', views.InventoryItemMatchUpdate.as_view(), name='InventoryItemMatchUpdate'),
    path('item/<int:pk>/quickedit/modal/', views.InventoryItemQuickEditModal.as_view(), name='InventoryItemQuickEditModal'),
    path('item/<int:pk>/update/', views.InventoryItemUpdate.as_view(), name='InventoryItemUpdate'),
    # path('item/<int:pk>/delete/', views.InventoryItemDelete.as_view(), name='InventoryItemDelete'),
    path('item/<int:pk>/', views.InventoryItemDetail.as_view(), name='InventoryItemDetail'),
    path('item/<int:pk>/modal/', views.InventoryItemDetailModal.as_view(), name='InventoryItemDetailModal'),
    path('item/new/', views.NewInventoryItem.as_view(), name='NewInventoryItem'),
    path('items/', views.InventoryItemList.as_view(), name='InventoryItemList'),
    path('movelog/', views.InventoryMovementLogList.as_view(), name='InventoryMovementLog'),
    ]

backend/config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from . import views

urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('cms-admin/', admin.site.urls),
    path('cms-auth/', include('django.contrib.auth.urls')),
    path('cmsacc/', include('cmsacc.urls')),
    path('cmsinv/', include('cmsinv.urls')),
    path('cmssys/', include('cmssys.urls')),
    path('drugdb/', include('drugdb.urls')),
    path('inventory/', include('inventory.urls')),
    path('ledger/', include('ledger.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('', views.HomeSelectVendorView, name='home'),
    # path('', TemplateView.as_view(template_name='home.html'), name='home'),
]

backend/inventory/urls.py
from django.urls import path
from . import views

app_name = 'inventory'
urlpatterns = [
    path('category/new/', views.NewCategory.as_view(), name='NewCategory'),
    path('category/<int:pk>/update', views.CategoryUpdate.as_view(), name='CategoryUpdate'),
    path('category/<int:pk>/delete', views.CategoryDelete.as_view(), name='CategoryDelete'),
    path('category/', views.CategoryList.as_view(), name='CategoryList'),
    path('delivery/new/', views.NewDeliveryOrder.as_view(), name='NewDeliveryOrder'),
    path('delivery/new/modal/', views.NewDeliveryOrderModal.as_view(), name='NewDeliveryOrderModal'),
    # path('delivery/vendor/new/', views.NewDeliveryOrderSelectVendorView, name='NewDeliveryOrderSelectVendor'),
    path('delivery/items/', views.DeliveryItemList.as_view(), name='DeliveryItemList'),
    path('delivery/<int:delivery_id>/item/<int:pk>/delete/modal/', views.DeliveryItemDeleteModal.as_view(), name='DeliveryItemDeleteModal'),
    path('delivery/<int:delivery_id>/item/<int:pk>/update/modal/', views.DeliveryItemUpdateModal.as_view(), name='DeliveryItemUpdateModal'),
    path('delivery/<int:delivery_id>/item/<int:pk>/modal/', views.DeliveryItemDetailModal.as_view(), name='DeliveryItemDetailModal'),
    # path('delivery/<int:delivery_id>/item/<int:cmsitem_id>/add/', views.DeliveryOrderAddDeliveryItem.as_view(), name='DeliveryOrderAddDeliveryItem'),
    path('delivery/<int:delivery_id>/item/add/', views.DeliveryOrderAddDeliveryItem.as_view(), name='DeliveryOrderAddDeliveryItem'),
    path('delivery/<int:pk>/update/modal/', views.DeliveryOrderUpdateModal.as_view(), name='DeliveryOrderUpdateModal'),
    path('delivery/<int:pk>/delete/modal/', views.DeliveryOrderDeleteModal.as_view(), name='DeliveryOrderDeleteModal'),
    path('delivery/<int:delivery_id>/togglesynced/', views.DeliveryOrderToggleSynced, name='DeliveryOrderToggleSynced'),
    # path('delivery/<int:delivery_id>/item/<int:cmsitem_id>/add/', views.DeliveryOrderAddItemView, name='DeliveryOrderAddItem'),
    # path('delivery/<int:delivery_id>/new/modal/', views.DeliveryOrderAddDrugModal.as_view(), name='DeliveryOrderAddDrugModal'),
    path('delivery/<int:delivery_id>/', views.DeliveryOrderDetail, name='DeliveryOrderDetail'),
    path('delivery/', views.DeliveryOrderList.as_view(), name='DeliveryOrderList'),
    # path('item/new/<int:vendor_id>', views.NewItemFromVendor.as_view(), name='NewItemFromVendor'),
    path('item/new/', views.NewItem.as_view(), name='NewItem'),
    path('item/new/modal/', views.NewItemModal.as_view(), name='NewItemModal'),
    # path('item/selectdrug/', views.ItemSelectDrugView, name='ItemSelectDrugView'),
    path('item/<int:pk>/update/modal/', views.ItemUpdateModal.as_view(), name='ItemUpdateModal'),
    path('item/<int:pk>/delete/', views.ItemDelete.as_view(), name='ItemDelete'),
    path('item/<int:pk>', views.ItemDetail.as_view(), name='ItemDetail'),
    path('items/', views.ItemList.as_view(), name='ItemList'),
    path('stocktake/', views.StocktakeView, name='Stocktake'),
    # path('vendor/select/modal/', views.VendorSelectModal.as_view(), name='VendorSelectModal'),
    path('vendor/new/', views.NewVendor.as_view(), name='NewVendor'),
    # path('vendor/new/modal/', views.NewVendorModal.as_view(), name='NewVendorModal'),
    path('vendor/<int:pk>/update/modal', views.VendorUpdateModal.as_view(), name='VendorUpdateModal'),
    path('vendor/<int:pk>/update/', views.VendorUpdate.as_view(), name='VendorUpdate'),
    # path('vendor/<int:pk>/delete/', views.VendorDelete.as_view(), name='VendorDelete'),
    path('vendor/<int:pk>/delete/modal/', views.VendorDeleteModal.as_view(), name='VendorDeleteModal'),
    path('vendor/<int:pk>', views.VendorDetail.as_view(), name='VendorDetail'),
    path('vendors/', views.VendorList.as_view(), name='VendorList'),
]

backend/ledger/urls.py
from django.urls import path
from . import views

app_name = 'ledger'
urlpatterns = [
    path('expense/category/<int:pk>/update/', views.ExpenseCategoryUpdate.as_view(), name='ExpenseCategoryUpdate'),
    path('expense/category/', views.ExpenseCategoryList.as_view(), name='ExpenseCategoryList'),
    path('expense/export/csv/', views.ExpenseExportCsv, name='ExpenseExportCsv'),
    path('expense/<int:pk>/update/', views.ExpenseUpdate.as_view(), name='ExpenseUpdate'),
    path('expense/<int:pk>/update/modal/', views.ExpenseUpdateModal.as_view(), name='ExpenseUpdateModal'),
    path('expense/<int:pk>/delete/modal/', views.ExpenseDeleteModal.as_view(), name='ExpenseDeleteModal'),
    # path('expenses/vendor/<int:vendor_id>/new/', views.NewExpenseByVendorModal.as_view(), name='NewExpenseByVendorModal'),
    path('expense/new/modal/', views.NewExpenseModal.as_view(), name='NewExpenseModal'),
    path('expense/new/selectvendor/', views.NewExpenseSelectVendorView, name='NewExpenseSelectVendor'),
    path('expense/new/delivery/<int:delivery_id>/modal/', views.DeliveryPaymentModal.as_view(), name='DeliveryPaymentModal'),
    path('expense/new/vendor/<int:vendor_id>/', views.NewDeliveryOrderPayment.as_view(), name='NewDeliveryOrderPayment'),
    path('expense/<int:expense_id>/add/delivery/<int:delivery_id>/', views.ExpenseAddDeliveryOrder, name='ExpenseAddDeliveryOrder'),
    path('expense/<int:expense_id>/remove/delivery/<int:delivery_id>/', views.ExpenseRemoveDeliveryOrder, name='ExpenseRemoveDeliveryOrder'),
    path('expense/<int:pk>/makepermanent', views.ExpenseConfirmPermanentModalView, name="ExpenseConfirmPermanentModal"),
    path('expense/<int:expense_id>/togglepermanent', views.ExpenseTogglePermanent, name="ExpenseTogglePermanent"),
    path('expense/<int:pk>/', views.ExpenseDetail.as_view(), name='ExpenseDetail'),
    path('expense/new/', views.NewExpense.as_view(), name='NewExpense'),
    path('expense/', views.ExpenseList.as_view(), name='ExpenseList'),
    path('income/<int:pk>/delete/modal/', views.IncomeDeleteModal.as_view(), name='IncomeDeleteModal'),
    path('income/<int:pk>/update/modal/', views.IncomeUpdateModal.as_view(), name='IncomeUpdateModal'),
    path('income/<int:pk>/', views.IncomeDetail.as_view(), name='IncomeDetail'),
    path('income/new/modal', views.NewIncomeModal.as_view(), name='NewIncomeModal'),
    path('income/', views.IncomeList.as_view(), name='IncomeList'),
    ]

backend/ledger/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from inventory.models import Vendor

class ExpenseCategory(models.Model):
    """
    Model definition for ExpenseCategory
    """
    name = models.CharField(max_length=255, unique=True)
    code = models.CharField(max_length=255, unique=True)
    description = models.CharField(max_length=255, blank=True, null=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['code','-active']
        verbose_name = 'Expense category'
        verbose_name_plural = 'Expense categories'
    
    @property
    def label(self):
        return '-'.join([self.code, self.name])

    def __str__(self):
        return f"{self.label}"

class PaymentMethod(models.Model):
    """
    Model definition for PaymentMethod
    E.g. Cash, Cheque
    """
    name = models.CharField(max_length=255, unique=True)
    description = models.CharField(max_length=255)

    class Meta:
        ordering = ['name']
        verbose_name = 'Payment method'

    def __str__(self):
        return f"{self.name}"

class LedgerEntry(models.Model):
    """Base model definition for Ledger Entries"""

    entry_date = models.DateField()
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.CharField(max_length=255, blank=True, null=True)
    remarks = models.TextField(blank=True, null=True)
    expected_date = models.DateField(verbose_name="Cheque/paid date", blank=True, null=True)
    permanent = models.BooleanField(default=False)
    trashed = models.BooleanField(default=False)
    # expected_date: refers to due/paid date, cheque date (for cheque expense)
    date_created = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)
    updated_by = models.CharField(max_length=255, blank=True, null=True)
    version = models.PositiveIntegerField(default=1)

    class Meta:
        ordering = ['-entry_date']
        verbose_name = 'Ledger entry'
        verbose_name_plural = 'Ledger entries'

    def __str__(self):
        return f"{self.entry_date} | ${self.amount}"

class Expense(LedgerEntry):
    """Model definition for Expense"""

    category = models.ForeignKey(
        ExpenseCategory, on_delete=models.PROTECT,
        blank=True, null=True
    )
    payee = models.CharField(max_length=255, blank=True, null=True)
    # vendor: can be the same as the payee; occasionally the payee name is different.
    vendor = models.ForeignKey(
        'inventory.Vendor', blank=True, null=True,
        on_delete = models.PROTECT
        )
    payment_method = models.ForeignKey(
        PaymentMethod, on_delete=models.PROTECT,
    )
    # payment_ref: used for cheque number or other
    payment_ref = models.CharField(verbose_name="Cheque/ref no.", max_length=255, blank=True, null=True)
    invoice_no = models.CharField(max_length=255, blank=True, null=True)
    invoice_date = models.DateField(blank=True, null=True)
    other_ref = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        ordering = ['-entry_date']
        verbose_name = 'Expense'
        verbose_name_plural = 'Expenses'

    @property
    def invoice_short(self):
        if self.invoice_no:
            invoices = self.invoice_no.split(',')
            if len(invoices) > 1:
                return f"{str(invoices[0])},[..+{len(invoices)-1}]"
            else:
                return self.invoice_no
        else:
            return None

    def get_absolute_url(self):
        return reverse('ledger:ExpenseDetail', kwargs={'pk': self.pk})

    def __str__(self):
        return f"{self.entry_date} | ${self.amount} - {self.payee}"

class IncomeCategory(models.Model):
    """
    Model definition for IncomeCategory
    """
    name = models.CharField(max_length=255, unique=True)
    code = models.CharField(max_length=255, unique=True)
    description = models.CharField(max_length=255, blank=True, null=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['code','-active']
        verbose_name = 'Income category'
        verbose_name_plural = 'Income categories'
    
    @property
    def label(self):
        return '-'.join([self.code, self.name])

    def __str__(self):
        return f"{self.label}"

class IncomeSource(models.Model):
    """
    Model definition for IncomeSource
    """
    name = models.CharField(max_length=255, unique=True)
    code = models.CharField(max_length=255, unique=True)
    account_no = models.CharField(max_length=255, blank=True, null=True)
    category = models.ForeignKey(
        IncomeCategory, on_delete=models.PROTECT,
        blank=True, null=True
    )
    description = models.CharField(max_length=255, blank=True, null=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['code','-active']
        verbose_name = 'Income source'
    
    @property
    def label(self):
        return '-'.join([self.code, self.name])

    def __str__(self):
        return f"{self.label}"

class Income(LedgerEntry):
    """Model definition for Income"""
    
    payer = models.ForeignKey(
        IncomeSource, on_delete=models.PROTECT
    )
    payment_method = models.ForeignKey(
        PaymentMethod, on_delete=models.PROTECT,
    )
    payment_ref = models.CharField(verbose_name="Cheque/ref no.", max_length=255, blank=True, null=True)
    invoice_no = models.CharField(max_length=255, blank=True, null=True)
    invoice_date = models.DateField(blank=True, null=True)
    other_ref = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        ordering = ['-entry_date']
        verbose_name = 'Income'

    def get_absolute_url(self):
        return reverse('ledger:IncomeDetail', kwargs={'pk': self.pk})

    def __str__(self):
        return f"{self.entry_date} | ${self.amount} - {self.payer}"

backend/ledger/templates/ledger/_deliveryorder_list_table.html
<table class="table table-hover table-sm table-striped">
    <thead>
        
        <tr>
            <th scope="col" width="8%">Invoice date/no.</th>
            <th scope="col" width="8%" class="text-center">Received date</th>
            <th scope="col" width="68%" colspan="5" class="text-center bg-secondary text-white">Purchase</th>
            <th scope="col" width="8%" class="text-right">Amount</th>
            <th scope="col" width="8%" class="text-right">Action</th>
        </tr>
        <tr>
            <th scope="col" colspan="2"></th>
            <th scope="col" colspan="5">
                <table width="100%">
                    <tr>
                        <th scope="col" width="45%" class="bg-light">Product name</th>
                        <th scope="col" width="10%" class="text-right bg-light">Quantity</th>
                        <th scope="col" width="10%" class="text-right bg-light">Bonus</th>
                        <th scope="col" width="10%" class="text-right bg-light">Std $</th>
                        <th scope="col" width="10%" class="text-right bg-light">Avg $</th>
                        <th scope="col" width="15%" class="text-right bg-light">Total $</th>
                    </tr>
                </table>
            </th>
           
            <th scope="col" colspan="2"></th>
        </tr>
    </thead>
    <tbody>
        {% for record in deliveryorder_list %}
        
        <tr>
            <td>
                <strong>{{ record.invoice_date|date:"d-m-Y" }}</strong>
                <br>
                {% if record.invoice_no %}<em>{{ record.invoice_no}}</em>
                {% else %}-
                {% endif %}
            </td>
            <td class="text-center">
                {{ record.received_date|date:"d-m-Y" }}
                <br>
                {% if not record.cms_synced and record.items %}
                <button
                class="btn_modal_trigger badge badge-warning ml-2 mt-0"
                data-id="{% url 'cmsinv:NewDeliveryFromDeliveryOrderModal' record.id %}?next={{ request.path }}"
                >Push to CMS
                </button>
                {% endif %}
            </td>
            <td colspan="5">
                {% if record.items %}
                <table width="100%">
                    {% for listitem in record.items %}
                    <tr>
                        <td width="45%">{{ listitem.name }}
                            <br>{{ listitem.items_per_purchase }}&nbsp;
                            {% if listitem.items_unit %}
                            {{ listitem.items_unit }} 
                            {% endif %} / {{ listitem.purchase_unit }}
                        </td>
                        <td width="10%" class="text-right">
                            {% if listitem.is_sample %}
                            <span class="badge badge-info ml-2 mt-0"
                            >Sample
                            </span>
                            {% else %}
                            {{ listitem.purchase_quantity }}
                            {% endif %}
                        </td>
                        <td width="10%" class="text-right">
                            {% if listitem.bonus_quantity %}
                            + {{ listitem.bonus_quantity }}
                            {% endif %}
                        </td>
                        <td width="10%" class="text-right">{{ listitem.standard_cost }}</td>
                        <td width="10%" class="text-right">{{ listitem.average_cost }}</td>
                        <td width="15%" class="text-right">{{ listitem.total_price }}</td>
                    </tr>
                    {% endfor %}
                </table>
                {% else %}
                  <p>
                    {% if record.remarks %}
                      Remarks: {{ record.remarks }}
                    {% endif %}
                    {% if record.other_ref %}
                      Other Ref: {{ record.other_ref }}
                    {% endif %}
                    </p>
                {% endif %}
            </td>
            <td class="text-right">{{ record.amount }}</td>
            <td class="text-right">
                <a href="{% url 'inventory:DeliveryOrderDetail' record.id %}" 
                  class="btn btn-sm btn-info"
                ><i class="fad fa-box-alt"></i>
                </a>
                {% if not expense_obj.permanent %}
                <a href="{% url 'ledger:ExpenseRemoveDeliveryOrder' expense_obj.id record.id %}"
                  class="btn btn-sm btn-warning"
                ><i class="fal fa-layer-minus"></i>
                </a>
                {% endif %}
            </td>
        </tr>

        {% endfor %}
        <tr>
            <th colspan="7" class="text-right">
                Total:
                {% if list_total != expense_obj.amount %}
                <span class="badge badge-danger ml-2 mt-0"
                >Not matching invoice amount
                </span>
                {% endif %}
            </th>
            <td class="text-right"><strong>{{ list_total }}</strong></td>
            <td colspan="2" class="text-center"></td>
        </tr>

    </tbody>
</table>

backend/ledger/templates/ledger/expense_detail.html
{% extends 'base.html' %}

{% block title %}
  Expense Record: {{ expense_obj.entry_date }}
{% endblock %}

{% block content %}
  {% include '_modal.html' %}

  <div class="card shadow">
    <div class="card-header text-white bg-info">
      <div class="d-flex justify-content-between align-items-center">
        <span>
          <i class="far fa-file-invoice-dollar" aria-hidden="true"></i>
          Expense on {{ expense_obj.entry_date }}
        </span>
        <span>
          {% if perms.view_expense %}
          <a
            href="{% url 'ledger:ExpenseList' %}"
            class="btn btn-sm btn-dark text-white"
          ><i class="fal fa-step-backward"></i>&nbsp;Expenses
          </a>
          {% endif %}
          <a
            href="{% url 'inventory:DeliveryOrderList' %}"
            class="btn btn-sm btn-dark text-white"
          ><i class="fal fa-step-backward"></i>&nbsp;Orders
          </a>
          <a
            href="{% url 'inventory:DeliveryItemList' %}"
            class="btn btn-sm btn-dark text-white"
          ><i class="fal fa-step-backward"></i>&nbsp;Drugs
          </a>
          {% if not expense_obj.permanent or user.is_staff %}
          <button
            class="btn_modal_trigger btn btn-sm btn-light"
            data-id="{% url 'ledger:ExpenseUpdateModal' expense_obj.id %}?next={{ request.path }}"
          >Edit
          </button>
          {% endif %}
        </span>
      </div>
    </div>
    <div class="card-body">
      <div class="form-row border-bottom pb-2 mb-2">
        <div class="col-md-6 mb-0"><strong>{{ expense_obj.payee }}</strong>
          {% if expense_obj.vendor.is_supplier %}
          <a
            class="badge badge-secondary ml-2 my-0"
            href="{% url 'inventory:NewDeliveryOrder' %}?vendor={{ expense_obj.vendor.id }}"
          >Add new delivery
          </a>
          <a
            class="badge badge-light ml-2 my-0"
            href="{% url 'ledger:NewDeliveryOrderPayment' expense_obj.vendor.id %}"
          >New Payment 
          </a>
          {% else %}
          <a
            class="badge badge-light ml-2 my-0"
            href="{% url 'ledger:NewExpense' %}?vendor={{ expense_obj.vendor.id }}"
          >New Expense
          </a>
          {% endif %}
        </div>
        <div class="col-md-2 mb-0">Amount</div>
        <div class="col-md-4 mb-0">
          <div class="d-flex justify-content-between">
          <span><strong>$ {{ expense_obj.amount }}</strong></span>
          <div>
            {% if not expense_obj.permanent and user.is_staff %}
            <a
              class="btn btn-sm badge badge-warning ml-2 mt-0"
              href="{% url 'ledger:ExpenseTogglePermanent' expense_obj.id %}"
            >Set permanent 
            </a>
            {% elif not expense_obj.permanent %}
            <button
              class="btn_modal_trigger badge badge-warning" type="button"
              data-id="{% url 'ledger:ExpenseConfirmPermanentModal' expense_obj.id %}?next={{ request.path }}"
            >
              Make permanent
            </button>
            {% elif user.is_staff %}
            <a
              class="btn btn-sm badge badge-danger ml-2 mt-0"
              href="{% url 'ledger:ExpenseTogglePermanent' expense_obj.id %}"
            >Unset permanent 
            </a>
            {% endif %}
            {% if expense_obj.expected_date %}
            <span class="badge badge-success">Paid</span>
            {% endif %}
          </div>
          </div>
        </div>
      </div>
      <div class="form-row">
        <div class="col-md-2 mb-0">Description</div>
        <div class="col-md-4 mb-0">{{ expense_obj.description }}</div>
        <div class="col-md-2 mb-0">Entry Date</div>
        <div class="col-md-4 mb-0">{{ expense_obj.entry_date|date:"d-m-Y" }}</div>
      </div>
      <div class="form-row">
        <div class="col-md-2 mb-0">Category</div>
        <div class="col-md-4 mb-0">{{ expense_obj.category.name }}</div>
        
        <div class="col-md-2 mb-0">Invoice Date</div>
        <div class="col-md-4">{{ expense_obj.invoice_date |date:"d-m-Y"}}</div>
      </div>
      <div class="form-row">
        <div class="col-md-2 mb-0">Invoice No.</div>
        <div class="col-md-4 mb-0">{{ expense_obj.invoice_no }}</div>
        <div class="col-md-2 mb-0">Cheque/Paid Date</div>
        <div class="col-md-4 mb-0 ">
          {{ expense_obj.expected_date|date:"d-m-Y"}}
          
        </div>
      </div>
      <div class="form-row">
        <div class="col-md-2 mb-0">Cheque No.</div>
        <div class="col-md-4 mb-0">{{ expense_obj.payment_ref }}</div>
        <div class="col-md-2 mb-0">Payment</div>
        <div class="col-md-4 mb-0">{{ expense_obj.payment_method.name }}</div>
      </div>
      <div class="form-row">
        <div class="col-md-2 mb-0">Remarks</div>
        <div class="col-md-4 mb-0">{{ expense_obj.remarks }}</div>
        <div class="col-md-2 mb-0">Other Ref</div>
        <div class="col-md-4 mb-0">{{ expense_obj.other_ref }}</div> 
      </div>
      <hr>
      {% if deliveryorder_list %}
          {% include 'ledger/_deliveryorder_list_table.html' %}
      {% elif expense_obj.catetegory.name == "Drugs" %}    
      <div class="alert alert-secondary" role="alert">
        No delivery orders 
      </div>      
      {% endif %}
    </div>
  </div>
  {% if unpaid_deliveries_list %}
  {% include 'ledger/_unpaid_delivery_orders.html' %}
  {% elif expense_obj.category.name == "Drugs" %}
  <div class="alert alert-secondary" role="alert">
      No outstanding unpaid delivery orders 
  </div>
  {% endif %}
{% endblock %}

{% block extrascripts %}
<script type="text/javascript">
  $(document).ready(function () {
      $(".btn_modal_trigger").each(function() {
          $(this).modalForm({
              formURL: $(this).data('id')
          });
      });
  });
</script>
{% endblock %}

backend/ledger/templates/ledger/new_expense.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{{form.media}}

{% block content %}


<div class="card shadow">
    <div class="card-header">
      <div class="d-flex justify-content-between align-items-center">
        Add New Expense
        <span>
          {% if not vendor_obj %}
          <a href="{% url 'inventory:NewVendor' %}?next={{ request.get_full_path }}" class="btn btn-sm btn-info">New Vendor</a>
          {% endif %}
          <a
            href="javascript: history.go(-1)"
            id="btn_cancel"
          ><span aria-hidden="true">&times;</span>
          </a>
        </span>
      </div>
    </div>
    <div class="card-body">
        {% crispy form %}
    </div>
</div>

{% endblock %}

{% block extrascripts %}
<script type="text/javascript">
    $(document).ready(function () {
      $("#btn_set_paymentdt").click(function() {
        console.log('click');
        $("#id_expected_date").val($("#id_invoice_date").val());
      });
      $("#btn_save_details").click(function() {
        $('#form').submit()
      });

      $("#id_vendor").change(function() {
            $("#id_payee").val($("#id_vendor option:selected").text());
        });
      $(".date").datetimepicker({
          format: "YYYY-MM-DD",
      });
      $("#id_invoice_no").focus();
    });
</script>
{% endblock %}

backend/ledger/templates/ledger/new_expense_category.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
  Add New Category
{% endblock %}


{% block main %}

    <h1>Add New Expense Category</h1>
    {% crispy form %}
  
{% endblock %}

{% block sidebar %}

{% endblock %}