backend/cmsacc/urls.py
from django.urls import path
from . import views

app_name = 'cmsacc'
urlpatterns = [
    path('payments/today', views.PaymentsToday.as_view(), name='PaymentToday'),
    ]

backend/cmsinv/urls.py
from django.urls import path
from . import views

app_name = 'cmsinv'
urlpatterns = [
    path('delivery/new/fromorder/<int:delivery_id>/modal/', views.NewDeliveryFromDeliveryOrderModalView, name='NewDeliveryFromDeliveryOrderModal'),
    path('suppliers/', views.SupplierList.as_view(), name='SupplierList'),
    path('supplier/<int:pk>/quickedit/modal/', views.SupplierQuickEditModal.as_view(), name='SupplierQuickEditModal'),
    # path('item/match/delivery/<int:delivery_id>/', views.MatchDeliveryInventoryItemList.as_view(), name='MatchDeliveryInventoryItemList'), # Non-CMS Delivery
    # path('item/match/<str:reg_no>/', views.MatchInventoryItemList.as_view(), name='MatchInventoryItemList'),
    # path('item/match/<int:pk>/update/', views.InventoryItemMatchUpdate.as_view(), name='InventoryItemMatchUpdate'),
    path('item/<int:pk>/quickedit/modal/', views.InventoryItemQuickEditModal.as_view(), name='InventoryItemQuickEditModal'),
    path('item/<int:pk>/update/', views.InventoryItemUpdate.as_view(), name='InventoryItemUpdate'),
    # path('item/<int:pk>/delete/', views.InventoryItemDelete.as_view(), name='InventoryItemDelete'),
    path('item/<int:pk>/', views.InventoryItemDetail.as_view(), name='InventoryItemDetail'),
    path('item/<int:pk>/modal/', views.InventoryItemDetailModal.as_view(), name='InventoryItemDetailModal'),
    path('item/new/', views.NewInventoryItem.as_view(), name='NewInventoryItem'),
    path('items/', views.InventoryItemList.as_view(), name='InventoryItemList'),
    path('movelog/', views.InventoryMovementLogList.as_view(), name='InventoryMovementLog'),
    ]

backend/config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from . import views

urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('cms-admin/', admin.site.urls),
    path('cms-auth/', include('django.contrib.auth.urls')),
    path('cmsacc/', include('cmsacc.urls')),
    path('cmsinv/', include('cmsinv.urls')),
    path('cmssys/', include('cmssys.urls')),
    path('drugdb/', include('drugdb.urls')),
    path('inventory/', include('inventory.urls')),
    path('ledger/', include('ledger.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('', views.HomeSelectVendorView, name='home'),
    # path('', TemplateView.as_view(template_name='home.html'), name='home'),
]

backend/drugdb/urls.py
from django.urls import path
from . import views

app_name = 'drugdb'
urlpatterns = [
    path('', views.RegisteredDrugList.as_view(), name='DrugList'),
    path('drug/<str:reg_no>/match/', views.DrugDetailMatch.as_view(), name='DrugDetailMatch'),
    path('drug/<str:reg_no>/link/<int:cmsitem_id>/', views.LinkCMSItemModalView, name='LinkCMSItemModal'),
]

backend/inventory/urls.py
from django.urls import path
from . import views

app_name = 'inventory'
urlpatterns = [
    path('category/new/', views.NewCategory.as_view(), name='NewCategory'),
    path('category/<int:pk>/update', views.CategoryUpdate.as_view(), name='CategoryUpdate'),
    path('category/<int:pk>/delete', views.CategoryDelete.as_view(), name='CategoryDelete'),
    path('category/', views.CategoryList.as_view(), name='CategoryList'),
    path('delivery/new/', views.NewDeliveryOrder.as_view(), name='NewDeliveryOrder'),
    path('delivery/new/modal/', views.NewDeliveryOrderModal.as_view(), name='NewDeliveryOrderModal'),
    # path('delivery/vendor/new/', views.NewDeliveryOrderSelectVendorView, name='NewDeliveryOrderSelectVendor'),
    path('delivery/items/', views.DeliveryItemList.as_view(), name='DeliveryItemList'),
    path('delivery/<int:delivery_id>/item/<int:pk>/delete/modal/', views.DeliveryItemDeleteModal.as_view(), name='DeliveryItemDeleteModal'),
    path('delivery/<int:delivery_id>/item/<int:pk>/update/modal/', views.DeliveryItemUpdateModal.as_view(), name='DeliveryItemUpdateModal'),
    path('delivery/<int:delivery_id>/item/<int:pk>/modal/', views.DeliveryItemDetailModal.as_view(), name='DeliveryItemDetailModal'),
    # path('delivery/<int:delivery_id>/item/<int:cmsitem_id>/add/', views.DeliveryOrderAddDeliveryItem.as_view(), name='DeliveryOrderAddDeliveryItem'),
    path('delivery/<int:delivery_id>/item/add/', views.DeliveryOrderAddDeliveryItem.as_view(), name='DeliveryOrderAddDeliveryItem'),
    path('delivery/<int:pk>/update/modal/', views.DeliveryOrderUpdateModal.as_view(), name='DeliveryOrderUpdateModal'),
    path('delivery/<int:pk>/delete/modal/', views.DeliveryOrderDeleteModal.as_view(), name='DeliveryOrderDeleteModal'),
    path('delivery/<int:delivery_id>/togglesynced/', views.DeliveryOrderToggleSynced, name='DeliveryOrderToggleSynced'),
    # path('delivery/<int:delivery_id>/item/<int:cmsitem_id>/add/', views.DeliveryOrderAddItemView, name='DeliveryOrderAddItem'),
    # path('delivery/<int:delivery_id>/new/modal/', views.DeliveryOrderAddDrugModal.as_view(), name='DeliveryOrderAddDrugModal'),
    path('delivery/<int:delivery_id>/', views.DeliveryOrderDetail, name='DeliveryOrderDetail'),
    path('delivery/', views.DeliveryOrderList.as_view(), name='DeliveryOrderList'),
    # path('item/new/<int:vendor_id>', views.NewItemFromVendor.as_view(), name='NewItemFromVendor'),
    path('item/new/', views.NewItem.as_view(), name='NewItem'),
    path('item/new/modal/', views.NewItemModal.as_view(), name='NewItemModal'),
    # path('item/selectdrug/', views.ItemSelectDrugView, name='ItemSelectDrugView'),
    path('item/<int:pk>/update/modal/', views.ItemUpdateModal.as_view(), name='ItemUpdateModal'),
    path('item/<int:pk>/delete/', views.ItemDelete.as_view(), name='ItemDelete'),
    path('item/<int:pk>', views.ItemDetail.as_view(), name='ItemDetail'),
    path('items/', views.ItemList.as_view(), name='ItemList'),
    path('stocktake/', views.StocktakeView, name='Stocktake'),
    # path('vendor/select/modal/', views.VendorSelectModal.as_view(), name='VendorSelectModal'),
    path('vendor/new/', views.NewVendor.as_view(), name='NewVendor'),
    # path('vendor/new/modal/', views.NewVendorModal.as_view(), name='NewVendorModal'),
    path('vendor/<int:pk>/update/modal', views.VendorUpdateModal.as_view(), name='VendorUpdateModal'),
    path('vendor/<int:pk>/update/', views.VendorUpdate.as_view(), name='VendorUpdate'),
    # path('vendor/<int:pk>/delete/', views.VendorDelete.as_view(), name='VendorDelete'),
    path('vendor/<int:pk>/delete/modal/', views.VendorDeleteModal.as_view(), name='VendorDeleteModal'),
    path('vendor/<int:pk>', views.VendorDetail.as_view(), name='VendorDetail'),
    path('vendors/', views.VendorList.as_view(), name='VendorList'),
]

backend/inventory/models.py
import pytz
from datetime import datetime
from django.db import models
from django.urls import reverse
from django.conf import settings
# from drugdb.models import RegisteredDrug
# from ledger.models import ExpenseCategory
from cmsinv.models import InventoryItem

class Category(models.Model):
    """
    Model for item category
    """
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    active = models.BooleanField(default=True)
    value = models.CharField(max_length=255, unique=True, null=True, blank=True)

    class Meta:
        ordering = ['value']
        verbose_name_plural = 'Categories'

    def __str__(self):
        return f"{self.value} | {self.name}"

    def get_absolute_url(self):
        return reverse('inventory:CategoryUpdate', kwargs={'pk': self.pk})

class Vendor(models.Model):
    """
    Model for vendor/suppliers
    """
    # Fields matching drugdb.Company
    name = models.CharField(unique=True, max_length=255, blank=True, null=True)
    address = models.TextField(blank=True, null=True)
    date_created = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)
    
    # Fields matching cmsinv.Supplier
    # Note: tel_home replaced by tel_main
    #       version converted from BigIntegerField to PositiveIntegerField
    version = models.PositiveIntegerField(default=1)
    contact_person = models.CharField(max_length=255, blank=True, null=True)
    email = models.CharField(max_length=255, blank=True, null=True)
    fax = models.CharField(max_length=255, blank=True, null=True)
    tel_main = models.CharField(max_length=255, blank=True, null=True)
    tel_mobile = models.CharField(max_length=255, blank=True, null=True)
    tel_office = models.CharField(max_length=255, blank=True, null=True)
    updated_by = models.CharField(max_length=255, blank=True, null=True)
    
    # Below commented field from cmsinv.Supplier omitted
    # supp_type = models.CharField(db_column='type', choices=SUPP_TYPE_CHOICES, max_length=255, blank=True, null=True)

    # Extra fields
    alias = models.CharField(unique=True, max_length=255, blank=True, null=True)
    account_no = models.CharField(max_length=255, blank=True, null=True)
    is_supplier = models.BooleanField(default=True)
    active = models.BooleanField(default=True)
    website = models.CharField(max_length=255, blank=True, null=True)
    remarks = models.TextField(blank=True, null=True)
    default_exp_category = models.ForeignKey(
        'ledger.ExpenseCategory', on_delete=models.PROTECT,
        verbose_name="Expense category",
        blank=True, null=True
    )
    default_description = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        ordering = ['name']
        permissions = (
            ('can_view_supplier', 'Can view supplier'),
            ('can_change_supplier', 'Can change supplier'),
        )
    def get_absolute_url(self):
        return reverse('inventory:VendorUpdate', kwargs={'pk': self.pk})

    def __str__(self):
        return f"{self.name}"

class ItemType(models.Model):
    """
    Model for type of inventory items, correlates to cmsinv.InventoryItemType
    To reserve id=1 for Drug, id=2 for Consumable
    """
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    active = models.BooleanField(default=True)
    value = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ['id']
        verbose_name = 'Item type'

    def __str__(self):
        return f"{self.value} | {self.name}"

class Item(models.Model):
    """
    Model to link CMS inventory item from external database, registered drug
    """
    
    name = models.CharField(max_length=255)  
    # name: Not enforce unique as Govt Drug Database and CMS product_name can have duplicate names
    note = models.CharField(max_length=255, blank=True, null=True)
    vendor = models.ForeignKey(
        Vendor, on_delete=models.PROTECT,
        blank=True, null=True,
    )
    cmsid = models.PositiveIntegerField(blank=True, null=True)
    reg_no = models.CharField(max_length=255, blank=True, null=True)
    item_type = models.ForeignKey(
        ItemType, on_delete=models.PROTECT,
        blank=True, null=True,
    )
    category = models.ForeignKey(
        Category, on_delete=models.PROTECT,
        blank=True, null=True,
    )
    date_created = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(blank=True, null=True)
    updated_by = models.CharField(max_length=255, blank=True, null=True)
    is_active = models.BooleanField(default=True)
    version = models.PositiveIntegerField(default=1)

    class Meta:
        ordering = ['name']

    def get_absolute_url(self):
        return reverse('inventory:ItemDetail', kwargs={'pk': self.pk})

    def __str__(self):
        return f"{self.name}"

class ItemsUnit(models.Model):
    """
    Records item units, e.g. pieces, bottles, mls etc.
    """
    short = models.CharField(max_length=20, unique=True)
    name = models.CharField(max_length=100, unique=True)

    class Meta:
        ordering = ['short']

    def __str__(self):
        return f"{self.short}: {self.name}"


class DeliveryOrder(models.Model):
    """
    Records delivery orders
    """
    invoice_no = models.CharField(max_length=255, blank=True, null=True)
    invoice_date = models.DateField(blank=True, null=True)
    items = models.ManyToManyField(
        Item, through='DeliveryItem',
        related_name='delivery_orders',
        blank=True)
    received_date = models.DateField(blank=True, null=True)
    received_by = models.CharField(max_length=255, blank=True, null=True)
    vendor = models.ForeignKey(
        Vendor, 
        on_delete = models.PROTECT
        )
    amount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    is_paid = models.BooleanField(default=False)
    bill = models.ForeignKey(
        'ledger.Expense', on_delete=models.PROTECT,
        blank=True, null=True,
    )
    due_date = models.DateField(blank=True, null=True)
    other_ref = models.CharField(max_length=255, blank=True, null=True)
    remarks = models.TextField(blank=True, null=True)
    date_created = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)
    updated_by = models.CharField(max_length=255, blank=True, null=True)
    cms_synced = models.BooleanField(default=False)
    cms_delivery_id = models.BigIntegerField(blank=True, null=True, default=None)
    version = models.PositiveIntegerField(default=1)

    @property
    def item_summary(self):
        return ', '.join(item.name for item in self.items.all())

    @property
    def items_total(self):
        total = 0
        for listitem in self.delivery_items.all():
            total += listitem.total_price
        return total

    class Meta:
        ordering = ['-invoice_date']

    def __str__(self):
        if self.vendor:
            return f"{self.received_date} : ${self.amount} | {self.vendor.name}"
        else:
            return f"{self.received_date} : ${self.amount}"

    def get_absolute_url(self):
        return reverse('inventory:DeliveryOrderDetail', kwargs={'pk': self.pk})


class DeliveryItem(models.Model):
    """
    Records item purchase transactions per DeliveryOrder
    """
    PACK = 'PACK'
    BOX = 'BOX'

    PURCHASE_UNIT_CHOICES = [
        (PACK, 'Pack'),
        (BOX, 'Box'),
    ]

    AMPOULE = 'AMPOULE'
    BOTTLE = 'BOTTLE'
    BOX = 'BOX'
    CAPSULE = 'CAP'
    DOSE = 'DOSE'
    GRAM = 'GRAM'
    INJECTION = 'INJECTION'
    MG = 'MG'
    ML = 'ML'
    PACK = 'PACK'
    TAB = 'TAB'
    TUBE = 'TUBE'
    UNIT = 'UNIT'
    VIAL = 'VIAL'

    ITEMS_UNIT_CHOICES = [
        (AMPOULE, 'Ampoule'),
        (BOTTLE, 'Bottle'),
        (BOX, 'Box'),
        (CAPSULE, 'Cap'),
        (DOSE, 'Dose'),
        (GRAM, 'gram'),
        (INJECTION, 'Injection'),
        (MG, 'mg'),
        (ML, 'mL'),
        (PACK, 'Pack'),
        (TAB, 'Tablet'),
        (TUBE, 'Tube'),
        (UNIT, 'Unit'),
        (VIAL, 'Vial'),
    ]

    item = models.ForeignKey(
        Item, related_name='delivery_items',
        on_delete=models.CASCADE,
    )
    delivery_order = models.ForeignKey(
        DeliveryOrder, related_name='delivery_items',
        on_delete = models.CASCADE,
    )
    purchase_quantity = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    purchase_unit = models.CharField(max_length=100, choices=PURCHASE_UNIT_CHOICES, default=BOX)
    bonus_quantity = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    unit_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    discount = models.DecimalField(max_digits=4, decimal_places=2, default=0)
    # discount: percentage discount applied to unit_price in calculation of total; e.g. 25 = 25% off
    items_per_purchase = models.DecimalField(max_digits=10, decimal_places=0, default=1)
    # items_per_purchase: number of granular items per unit of purchase. E.g. 1 pack can contain 100 items
    items_unit = models.CharField(max_length=10, choices=ITEMS_UNIT_CHOICES, blank=True, null=True)
    batch_num = models.CharField(max_length=100, blank=True, null=True)
    other_ref = models.CharField(max_length=100, blank=True, null=True)
    expiry_month = models.CharField(verbose_name='Expiry (YYYYMM)', max_length=8, default="", blank=True, null=True)
    is_sample = models.BooleanField(default=False)
    # expiry_month: format of yyyymm, or yyyymmdd; to supercede expiry_date
    version = models.PositiveIntegerField(default=1)

    # Calculated properties
    @property
    def total_price(self):
        """Total calculated price of purchased unit in transaction"""
        return round(self.purchase_quantity * self.unit_price * (1 - self.discount/100), 2)

    @property
    def items_quantity(self):

backend/inventory/templates/inventory/_deliveryorder_items.html
<!--
    Include Card for Delivery Items
    Requires:
    - deliveryitems_list
-->

{% if deliveryitems_list %}
<div class="card">
    <div class="card-body">
        <table class="table table-sm table-striped">
            <thead>
                <tr>
                    <th scope="col">Product name</th>
                    <th scope="col" class="text-center">Permit no.</th>
                    <th scope="col" class="text-center">Purchase</th>
                    <th scope="col" class="text-center">Bonus</th>
                    <th scope="col" class="text-center">Unit Price</th>
                    <th scope="col" class="text-right">Qty/Pack</th>
                    <th scope="col" class="text-right">Std Cost</th>
                    <th scope="col" class="text-right">Avg Cost</th>
                    <th scope="col" class="text-right">Total</th>
                    <th scope="col" class="text-center"></th>
                </tr>
            </thead>
            <tbody>
                {% for listitem in deliveryitems_list %}
                
                <tr>
                    <td>
                        {% if listitem.item.cmsid %}
                        <a class="btn-link"
                            href="{% url 'cmsinv:InventoryItemDetail' listitem.item.cmsid %}">
                            {{ listitem.item.name }}
                        </a>
                        <button
                            class="btn_modal_trigger btn btn-sm btn-link text-left"
                            data-id="{% url 'cmsinv:InventoryItemQuickEditModal' listitem.item.cmsid %}?next={{ request.path }}"  
                        ><i class="fad fa-edit"></i>
                        </button>
                        {% else %}
                        <a class="btn-link"
                            href="{% url 'inventory:ItemDetail' listitem.item.id %}">
                            {{ listitem.item.name }}
                        </a>
                        <button
                            class="btn_modal_trigger btn btn-sm btn-link text-left"
                            data-id="{% url 'inventory:ItemUpdateModal' listitem.item.id %}"  
                        ><i class="fad fa-edit"></i>
                        </button>
                        {% endif %}
                    </td>
                    <td class="text-center">
                        {% if listitem.item.reg_no %}
                        {{ listitem.item.reg_no }}
                        {% else %}-
                        {% endif %}
                    </td>
                    <td class="text-center">
                        {% if listitem.is_sample %}
                        <span class="badge badge-info ml-2 mt-0"
                        >Sample
                        </span>
                        {% else %}
                        {{ listitem.purchase_quantity|floatformat:2 }}
                        {% endif %}
                    </td>
                    <td class="text-center">
                        {% if listitem.bonus_quantity %}
                        {{ listitem.bonus_quantity|floatformat:2 }}
                        {% else %}-
                        {% endif %}
                    </td>
                    <td class="text-center">
                        $ {{ listitem.unit_price }}
                    </td>
                    <td class="text-right">
                        {{ listitem.items_per_purchase|floatformat }}
                        {% if listitem.items_unit %}
                        {{ listitem.items_unit|title}}
                        {% endif %}
                    </td>
                    <td class="text-right">$ {{ listitem.standard_cost }}</td>
                    <td class="text-right">$ {{ listitem.average_cost }}</td>
                    <td class="text-right">$ {{ listitem.total_price }}</td>
                    <td class="text-center">
                        {% if not delivery_obj.cms_synced and perms.inventory.change_deliveryitem %}
                        <button type="button" class="btn_modal_trigger btn btn-sm btn-info"
                            data-id="{% url 'inventory:DeliveryItemUpdateModal' delivery_id=delivery_obj.id pk=listitem.id %}"
                        ><i class="fad fa-edit"></i>
                        </button>
                        {% else %}
                        <button type="button" class="btn_modal_trigger btn btn-sm btn-info"
                            data-id="{% url 'inventory:DeliveryItemDetailModal' delivery_id=delivery_obj.id pk=listitem.id %}"
                        ><i class="fad fa-file"></i>
                        </button>
                        {% endif %}
                        {% if not delivery_obj.cms_synced and perms.inventory.delete_deliveryitem %}
                        <button type="button" 
                            class="btn_modal_trigger btn btn-sm btn-danger"
                            data-id="{% url 'inventory:DeliveryItemDeleteModal' delivery_id=delivery_obj.id pk=listitem.id %}" 
                        ><i class="fad fa-trash"></i>
                        </button>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
                <tr>
                    <th colspan="8" class="text-right">
                        Total:
                        {% if list_total != delivery_obj.amount %}
                        <span class="badge badge-danger ml-2 mt-0"
                        >Not matching invoice amount
                        </span>
                        {% endif %}
                    </th>
                    <td class="text-right"><strong>{{ list_total }}</strong></td>
                </tr>
    
    
            </tbody>
        </table>

    </div>
</div>
{% else %}
<div class="alert alert-secondary" role="alert">
    No Drug Delivery Items Record 
</div>
{% endif %}

backend/inventory/templates/inventory/_deliveryorder_summary.html
<div class="card shadow">
  <div class="card-header text-white bg-info">
    <div class="d-flex justify-content-between align-items-center">
      <span>
        <i class="fad fa-box-alt" aria-hidden="true"></i>
        Delivery on {{ delivery_obj.received_date }}
      </span>
      <span>
        {% if perms.ledger.can_view_expense %}
        <a
          href="{% url 'ledger:ExpenseList' %}"
          class="btn btn-sm btn-dark text-white"
        ><i class="fal fa-step-backward"></i>&nbsp;Expenses
        </a>
        {% endif %}
        <a
          href="{% url 'inventory:DeliveryOrderList' %}"
          class="btn btn-sm btn-dark text-white"
        ><i class="fal fa-step-backward"></i>&nbsp;Orders
        </a>
        <a
          href="{% url 'inventory:DeliveryItemList' %}"
          class="btn btn-sm btn-dark text-white"
        ><i class="fal fa-step-backward"></i>&nbsp;Drugs
        </a>
        {% if not delivery_obj.cms_synced and perms.inventory.change_deliveryorder %}
        <button
          class="btn_modal_trigger btn btn-sm btn-light"
          data-id="{% url 'inventory:DeliveryOrderUpdateModal' delivery_obj.id %}"
        >Edit
        </button>
        {% endif %}
       
        {% if delivery_obj.bill %}
        <button
          class="btn_modal_trigger btn btn-sm btn-secondary"
          data-id="{% url 'ledger:DeliveryPaymentModal' delivery_obj.id %}"
        >Bill
        </button>
        {% elif delivery_obj.amount == 0 %}
        <button
          class="btn_modal_trigger btn btn-sm btn-secondary disabled" disabled
          data-id=""
        >Free
        </button> 
        {% else %}
        <a
          class="btn btn-sm btn-secondary"
          href="{% url 'ledger:NewDeliveryOrderPayment' delivery_obj.vendor.id %}"
        >Payment
        </a>
        {% endif %}
      </span>
    </div>
  </div>
  <div class="card-body">
    <div class="form-row">
      <div class="col-md-2 mb-0">Supplier</div>
      <div class="col-md-4 mb-0">
        {{ delivery_obj.vendor.name }}
        <a
          class="badge badge-secondary ml-2 mt-0"
          href="{% url 'inventory:NewDeliveryOrder' %}?vendor={{ delivery_obj.vendor.id }}"
        >Add new delivery
        </a>
      </div>
      <div class="col-md-2 mb-0">Received Date</div>
      <div class="col-md-2 mb-0">{{ delivery_obj.received_date|date:'d-m-Y'}}</div>
      <div class="col-md-2 text-right">
        {% if user.is_staff %}
        <a
          class="btn btn-sm badge badge-danger ml-2 mt-0"
          href="{% url 'inventory:DeliveryOrderToggleSynced' delivery_obj.id %}?next={{ request.path }}"
        >Toggle synced
        </a>
        {% endif %}
        {% if delivery_obj.cms_synced and not hide_cms_synced %}
        <span
          class="badge badge-success ml-1 mt-0"
        >CMS synced
        </span>
        {% elif not hide_cms_synced %}
        <button
          class="btn_modal_trigger badge badge-warning ml-1 mt-0"
          data-id="{% url 'cmsinv:NewDeliveryFromDeliveryOrderModal' delivery_obj.id %}?next={{ request.path }}"
        >Push to CMS
        </button>
        {% endif %}
        
      </div>
    </div>
    <div class="form-row">
      <div class="col-md-2 mb-0">Invoice No.</div>
      <div class="col-md-4 mb-0">{{ delivery_obj.invoice_no }}</div>
      <div class="col-md-2 mb-0">Invoice Date</div>
      <div class="col-md-2 mb-0">{{ delivery_obj.invoice_date|date:'d-m-Y' }}</div>
      <div class="col-md-2 text-right">
        {% if delivery_obj.is_paid %}
        <span class="badge badge-success">Paid</span>
        {% elif delivery_obj.amount == 0 and not hide_cms_synced %}
        <span class="badge badge-secondary">Bonus/Free</span>
        {% elif not hide_cms_synced %}
        <span class="badge badge-danger">Due</span>
        {% endif %}
      </div>
    </div>
    <div class="form-row">
      <div class="col-md-2 mb-0">Amount&nbsp;
        
      </div>
      <div class="col-md-4 mb-0">$ {{ delivery_obj.amount }}</div>
      <div class="col-md-2 mb-0">Due Date</div>
      <div class="col-md-4 mb-0">{{ delivery_obj.due_date|date:'d-m-Y' }}</div>
    </div>
    <div class="form-row">
      <div class="col-md-2 mb-0">Remarks</div>
      <div class="col-md-4 mb-0">
        {% if delivery_obj.remarks %}
        {{ delivery_obj.remarks }}
        {% else %}-
        {% endif %}
      </div>
      <div class="col-md-2 mb-0">Other Ref</div>
      <div class="col-md-4 mb-0">
        {% if delivery_obj.other_ref %}
        {{ delivery_obj.other_ref }}
        {% else %}-
        {% endif %}
      </div>
    </div>
  </div>
</div>

backend/inventory/templates/inventory/new_vendor_modal.html
{% load crispy_forms_tags %}
<div class="modal-header">
    <h3 class="modal-title">Add New Vendor</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  
  <div class="modal-body">
    {% crispy form %}
    {{form.media}}
  </div>
  
  <div class="modal-footer">
  </div>