backend/cmsacc/urls.py
from django.urls import path
from . import views

app_name = 'cmsacc'
urlpatterns = [
    path('payments/today', views.PaymentsToday.as_view(), name='PaymentToday'),
    ]

backend/cmsinv/urls.py
from django.urls import path
from . import views

app_name = 'cmsinv'
urlpatterns = [
    path('delivery/new/fromorder/<int:delivery_id>/modal/', views.NewDeliveryFromDeliveryOrderModalView, name='NewDeliveryFromDeliveryOrderModal'),
    path('suppliers/', views.SupplierList.as_view(), name='SupplierList'),
    path('supplier/<int:pk>/quickedit/modal/', views.SupplierQuickEditModal.as_view(), name='SupplierQuickEditModal'),
    # path('item/match/delivery/<int:delivery_id>/', views.MatchDeliveryInventoryItemList.as_view(), name='MatchDeliveryInventoryItemList'), # Non-CMS Delivery
    # path('item/match/<str:reg_no>/', views.MatchInventoryItemList.as_view(), name='MatchInventoryItemList'),
    # path('item/match/<int:pk>/update/', views.InventoryItemMatchUpdate.as_view(), name='InventoryItemMatchUpdate'),
    path('item/<int:pk>/quickedit/modal/', views.InventoryItemQuickEditModal.as_view(), name='InventoryItemQuickEditModal'),
    path('item/<int:pk>/update/', views.InventoryItemUpdate.as_view(), name='InventoryItemUpdate'),
    # path('item/<int:pk>/delete/', views.InventoryItemDelete.as_view(), name='InventoryItemDelete'),
    path('item/<int:pk>/', views.InventoryItemDetail.as_view(), name='InventoryItemDetail'),
    path('item/<int:pk>/modal/', views.InventoryItemDetailModal.as_view(), name='InventoryItemDetailModal'),
    path('item/new/', views.NewInventoryItem.as_view(), name='NewInventoryItem'),
    path('items/', views.InventoryItemList.as_view(), name='InventoryItemList'),
    path('movelog/', views.InventoryMovementLogList.as_view(), name='InventoryMovementLog'),
    ]

backend/config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from . import views

urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('cms-admin/', admin.site.urls),
    path('cms-auth/', include('django.contrib.auth.urls')),
    path('cmsacc/', include('cmsacc.urls')),
    path('cmsinv/', include('cmsinv.urls')),
    path('cmssys/', include('cmssys.urls')),
    path('drugdb/', include('drugdb.urls')),
    path('inventory/', include('inventory.urls')),
    path('ledger/', include('ledger.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('', views.HomeSelectVendorView, name='home'),
    # path('', TemplateView.as_view(template_name='home.html'), name='home'),
]

backend/drugdb/urls.py
from django.urls import path
from . import views

app_name = 'drugdb'
urlpatterns = [
    path('', views.RegisteredDrugList.as_view(), name='DrugList'),
    path('drug/<str:reg_no>/match/', views.DrugDetailMatch.as_view(), name='DrugDetailMatch'),
    path('drug/<str:reg_no>/link/<int:cmsitem_id>/', views.LinkCMSItemModalView, name='LinkCMSItemModal'),
]

backend/ledger/urls.py
from django.urls import path
from . import views

app_name = 'ledger'
urlpatterns = [
    path('expense/category/<int:pk>/update/', views.ExpenseCategoryUpdate.as_view(), name='ExpenseCategoryUpdate'),
    path('expense/category/', views.ExpenseCategoryList.as_view(), name='ExpenseCategoryList'),
    path('expense/export/csv/', views.ExpenseExportCsv, name='ExpenseExportCsv'),
    path('expense/<int:pk>/update/', views.ExpenseUpdate.as_view(), name='ExpenseUpdate'),
    path('expense/<int:pk>/update/modal/', views.ExpenseUpdateModal.as_view(), name='ExpenseUpdateModal'),
    path('expense/<int:pk>/delete/modal/', views.ExpenseDeleteModal.as_view(), name='ExpenseDeleteModal'),
    # path('expenses/vendor/<int:vendor_id>/new/', views.NewExpenseByVendorModal.as_view(), name='NewExpenseByVendorModal'),
    path('expense/new/modal/', views.NewExpenseModal.as_view(), name='NewExpenseModal'),
    path('expense/new/selectvendor/', views.NewExpenseSelectVendorView, name='NewExpenseSelectVendor'),
    path('expense/new/delivery/<int:delivery_id>/modal/', views.DeliveryPaymentModal.as_view(), name='DeliveryPaymentModal'),
    path('expense/new/vendor/<int:vendor_id>/', views.NewDeliveryOrderPayment.as_view(), name='NewDeliveryOrderPayment'),
    path('expense/<int:expense_id>/add/delivery/<int:delivery_id>/', views.ExpenseAddDeliveryOrder, name='ExpenseAddDeliveryOrder'),
    path('expense/<int:expense_id>/remove/delivery/<int:delivery_id>/', views.ExpenseRemoveDeliveryOrder, name='ExpenseRemoveDeliveryOrder'),
    path('expense/<int:pk>/makepermanent', views.ExpenseConfirmPermanentModalView, name="ExpenseConfirmPermanentModal"),
    path('expense/<int:expense_id>/togglepermanent', views.ExpenseTogglePermanent, name="ExpenseTogglePermanent"),
    path('expense/<int:pk>/', views.ExpenseDetail.as_view(), name='ExpenseDetail'),
    path('expense/new/', views.NewExpense.as_view(), name='NewExpense'),
    path('expense/', views.ExpenseList.as_view(), name='ExpenseList'),
    path('income/<int:pk>/delete/modal/', views.IncomeDeleteModal.as_view(), name='IncomeDeleteModal'),
    path('income/<int:pk>/update/modal/', views.IncomeUpdateModal.as_view(), name='IncomeUpdateModal'),
    path('income/<int:pk>/', views.IncomeDetail.as_view(), name='IncomeDetail'),
    path('income/new/modal', views.NewIncomeModal.as_view(), name='NewIncomeModal'),
    path('income/', views.IncomeList.as_view(), name='IncomeList'),
    ]

backend/cmsinv/models.py
from django.db import models
from cmssys.models import CMSModel, CmsUser, TextBooleanField 
from datetime import timedelta
from django.utils import timezone
from django.conf import settings

# CMS INVENTORY/DRUGS Models

class Supplier(CMSModel):
    """
    Maps to CMS table: supplier_manufacturer
    Stores supplier/cert holder/manufacturer contact details
    """
    CERT_HOLDER = 'Certificate Holder'
    SUPPLIER = 'Supplier'
    MANUFACTURER = 'Manufacturer'
    SUPP_TYPE_CHOICES = [
        (CERT_HOLDER, 'Certificate Holder'),
        (SUPPLIER, 'Supplier'),
        (MANUFACTURER, 'Manufacturer'),
    ]

    version = models.BigIntegerField(default=0)
    address = models.TextField(blank=True, null=True)
    contact_person = models.CharField(max_length=255, blank=True, null=True)
    date_created = models.DateTimeField(editable=False)
    last_updated = models.DateTimeField()
    email = models.CharField(max_length=255, blank=True, null=True)
    fax = models.CharField(max_length=255, blank=True, null=True)
    name = models.CharField(unique=True, max_length=255, blank=True, null=True)
    tel_home = models.CharField(max_length=255, blank=True, null=True)
    tel_mobile = models.CharField(max_length=255, blank=True, null=True)
    tel_office = models.CharField(max_length=255, blank=True, null=True)
    supp_type = models.CharField(db_column='type', choices=SUPP_TYPE_CHOICES, max_length=255, blank=True, null=True)
    updated_by = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'supplier_manufacturer'
        app_label = 'cmsinv'
        ordering = ['name']

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('cmsinv.views.details', args=[str(self.id)])

    def __str__(self):
        return f"{self.name}"

    def save(self, *args, **kwargs):
        """On save, update timestamps with offset"""
        if not self.id:
            self.date_created = timezone.now() + timedelta(hours=settings.CMS_OFFSET_HRS) 
        self.last_updated = timezone.now() + timedelta(hours=settings.CMS_OFFSET_HRS)
        return super().save(*args, **kwargs)

class Advisory(CMSModel):
    """
    Maps to CMS table: advisory
    Stores drug advisory information
    """

    version = models.BigIntegerField(default=0)
    alias = models.CharField(unique=True, max_length=255)
    created_by = models.ForeignKey(
        'cmssys.CmsUser', on_delete=models.PROTECT, 
        db_column='created_by_id', blank=True, null=True
        )
    date_created = models.DateTimeField(editable=False)
    last_updated = models.DateTimeField()
    description = models.TextField()
    description_chinese = models.TextField(blank=True, null=True)
    is_public = models.BooleanField(default=True)
    updated_by = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'advisory'
        app_label = 'cmsinv'
        verbose_name_plural = 'Advisory list'

    def __str__(self):
        return f"{self.alias} | {self.description_chinese} / {self.description}"

    def save(self, *args, **kwargs):
        """On save, update timestamps with offset"""
        if not self.id:
            self.date_created = timezone.now() + timedelta(hours=settings.CMS_OFFSET_HRS) 
        self.last_updated = timezone.now() + timedelta(hours=settings.CMS_OFFSET_HRS)
        return super().save(*args, **kwargs)

class Instruction(CMSModel):
    """
    Maps to CMS table: instruction
    Stores medication instructions
    """

    version = models.BigIntegerField(default=0)
    alias = models.CharField(unique=True, max_length=255)
    created_by = models.ForeignKey(
        'cmssys.CmsUser', on_delete=models.PROTECT, 
        db_column='created_by_id', blank=True, null=True)

    date_created = models.DateTimeField(editable=False)
    last_updated = models.DateTimeField()
    description = models.TextField(blank=True, null=True)
    description_chinese = models.TextField(blank=True, null=True)
    is_public = models.BooleanField(default=True)
    updated_by = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'instruction'
        app_label = 'cmsinv'

    def __str__(self):
        return f"{self.alias} | {self.description_chinese} / {self.description}"

    def save(self, *args, **kwargs):
        """On save, update timestamps with offset"""
        if not self.id:
            self.date_created = timezone.now() + timedelta(hours=settings.CMS_OFFSET_HRS) 
        self.last_updated = timezone.now() + timedelta(hours=settings.CMS_OFFSET_HRS)
        return super().save(*args, **kwargs)

class InventoryItemType(CMSModel):
    """
    Maps to CMS table: inventory_item_type
    Stores inventory type, note that only type 1=Drug is used in the CMS app
    """

    version = models.BigIntegerField(default=0)
    active = models.BooleanField(default=True)
    name = models.CharField(max_length=255)
    value = models.CharField(max_length=255)

    class Meta:
        managed = False
        db_table = 'inventory_item_type'
        app_label = 'cmsinv'

    def __str__(self):
        return f"{self.id} | {self.name}"


class InventoryItem(CMSModel):
    """
    Maps to CMS table: inventory_item
    Stores details in inventory items, including current stock quantity
    """
    AMPOULE = 'AMPOULE'
    BOTTLE = 'BOTTLE'
    BOX = 'BOX'
    CAPSULE = 'CAP'
    DOSE = 'DOSE'
    GRAM = 'GRAM'
    INJECTION = 'INJECTION'
    MG = 'MG'
    ML = 'ML'
    PACK = 'PACK'
    TAB = 'TAB'
    TUBE = 'TUBE'
    UNIT = 'UNIT'
    VIAL = 'VIAL'

    ITEMS_UNIT_CHOICES = [
        (AMPOULE, 'Ampoule'),
        (BOTTLE, 'Bottle'),
        (BOX, 'Box'),
        (CAPSULE, 'Cap'),
        (DOSE, 'Dose'),
        (GRAM, 'gram'),
        (INJECTION, 'Injection'),
        (MG, 'mg'),
        (ML, 'mL'),
        (PACK, 'Pack'),
        (TAB, 'Tablet'),
        (TUBE, 'Tube'),
        (UNIT, 'Unit'),
        (VIAL, 'Vial'),
    ]

    version = models.BigIntegerField(default=0)
    advisory = models.ForeignKey(
        'Advisory', on_delete=models.PROTECT, 
        db_column='advisory_id', blank=True, null=True)
    
    alias = models.CharField(max_length=255, blank=True, null=True)
    avg_cost = models.FloatField(default=0)
    category = models.CharField(max_length=255, blank=True, null=True)

    # certificate_holder - CMS database accepts 'Supplier' or 'Certificate Holder' but not 'Manufacturer' 
    # in this field, need to add validation to enforce this
    certificate_holder = models.ForeignKey(
        'Supplier', on_delete=models.CASCADE, 
        db_column='certificate_holder_id'
        )
    clinic_drug_no = models.CharField(max_length=255, blank=True, null=True, unique=True)
    dangerous_sign = TextBooleanField(default=False)  # MySQL text field, behaves like Boolean
    date_created = models.DateTimeField(editable=False)
    last_updated = models.DateTimeField(blank=True, null=True)
    discontinue = TextBooleanField()  # MySQL text field, behaves like Boolean
    dosage = models.CharField(max_length=255, blank=True, null=True)
    duration = models.CharField(max_length=255, blank=True, null=True)
    expected_qty = models.FloatField(default=1000)
    expire_date = models.DateField(blank=True, null=True)
    frequency = models.CharField(max_length=255, blank=True, null=True)
    generic_name = models.CharField(max_length=255, blank=True, null=True)
    generic_name_chinese = models.CharField(max_length=255, blank=True, null=True)
    ingredient = models.TextField(blank=True, null=True)
    instruction = models.ForeignKey(
        'Instruction', on_delete=models.PROTECT, 
        db_column='instruction_id', 
        blank=True, null=True
        )

    # N.B. inventory_type is not ever used in CMS App - by default all are set to Null
    # To make use of this, to set as:
    # - "Drug": Registered Drug (reg_no)
    # - "Supplement": Health supplement and vitamins
    # - "Nutrition": Nutritional supplement, e.g. Ensure
    DRUG = 'Drug'
    SUPP = 'Supplement'
    INVENTORY_TYPE_CHOICES = [
        (DRUG, 'Drug'),         # Registered Drug
        (SUPP, 'Supplement'),   # Health supplements, vitamins, etc.
    ]

    inventory_type = models.CharField(choices=INVENTORY_TYPE_CHOICES, max_length=255, blank=True, null=True)
    is_clinic_drug_list = TextBooleanField()  # MySQL text field, behaves like Boolean
    is_master_drug_list = TextBooleanField()  # MySQL text field, behaves like Boolean
    label_name = models.CharField(max_length=255, blank=True, null=True)
    label_name_chinese = models.CharField(max_length=255, blank=True, null=True)
    location = models.CharField(max_length=255, blank=True, null=True)
    mini_dispensary_unit = models.FloatField(default=0)
    mini_dosage_unit = models.FloatField(default=0)
    product_name = models.CharField(max_length=255, blank=True, null=True) # CMS product_name is not unique
    product_name_chinese = models.CharField(max_length=255, blank=True, null=True)
    registration_no = models.CharField(unique=True, max_length=255, blank=True, null=True)
    remarks = models.TextField(blank=True, null=True)
    reorder_level = models.FloatField(default=100)
    reorder_status = models.CharField(max_length=255, blank=True, null=True)
    standard_cost = models.FloatField(default=0)
    stock_qty = models.FloatField(default=0)
    unit = models.CharField(max_length=255, choices=ITEMS_UNIT_CHOICES, blank=True, null=True)
    unit_price = models.FloatField(default=0)
    updated_by = models.CharField(max_length=255, blank=True, null=True)
    priority = models.FloatField(default=0, blank=True, null=True)

    # inventory_item_type / type_id - Only type_id=1 (Drug) is ever used in the CMS App
    inventory_item_type = models.ForeignKey(
        'InventoryItemType', on_delete=models.PROTECT,
        default=1, 

backend/cmsinv/templates/cmsinv/_inventory_item_list_table.html
<!--
    Include Table for List of matching CMS Inventory Items
    Requires:
    - match_item_list_obj
-->
<table class="table table-sm table-striped">
    <thead>
        <tr>
            <th scope="col" width="10%">Ref no.</th>
            <th scope="col" width="20%">Alias/CertHolder</th>
            <th scope="col" width="20%">Product/Label</th>
            <th scope="col" width="26%">Generic/Ingredients</th>
            <th scope="col" width="8%" class="text-center">Stock Qty</th>
            <th scope="col" width="8%" class="text-center">Cost (Avg)</th>
            <th scope="col" width="8%" class="text-right">Action</th>
        </tr>
    </thead>
    <tbody>
        {% for cmsitem in match_item_list_obj %}
        
        <tr 
            {% if cmsitem.discontinue %}
            class="table-secondary text-muted"
            {% endif %}
        >
            <td><b>{{ cmsitem.registration_no }}</b>
                {% if cmsitem.discontinue %}
                <br><span class="badge badge-secondary">Inactive</span>
                {% else %}
                <br>{{ cmsitem.clinic_drug_no }}
            </td>
                {% endif %}
            <td>
                <b>{{ cmsitem.alias }}</b>
                <br>{{ cmsitem.certificate_holder }}
            </td>
            <td><b>{{ cmsitem.product_name }}</b>
            <br>{{ cmsitem.label_name }}</td>
            <td>
                <b>{{ cmsitem.generic_name }}</b>
                <br>{{ cmsitem.ingredient }}
            </td>
            <td class="text-center">
                {{ cmsitem.stock_qty }}
            </td>
            <td class="text-center">
                {% if cmsitem.standard_cost %}
                {{ cmsitem.standard_cost }}
                {% else %}-
                {% endif %}
                <br>({% if cmsitem.avg_cost %}{{ cmsitem.avg_cost}}{% else %} - {% endif %})
            </td>
            <td class="item-action-cell text-right">
                {% if user.is_staff %}
                <button
                  class="btn_modal_trigger btn btn-sm btn-secondary"
                  data-id="{% url 'cmsinv:InventoryItemQuickEditModal' cmsitem.pk %}?next={{ request.path }}"  
                ><i class="far fa-file-edit"></i>
                </button>
                <button
                  class="btn_modal_trigger btn btn-sm btn-info"
                  data-id="{% url 'cmsinv:InventoryItemDetailModal' cmsitem.pk %}?next={{ request.path }}"  
                ><i class="fad fa-file"></i>
                </button>
                {% endif %}
                <a
                    class="btn btn-sm btn-primary" 
                    href="{% url 'cmsinv:InventoryItemDetail' cmsitem.pk %}?next={{ request.path }}"
                ><i class="far fa-file-alt"></i>
                </a>
            </td>
        </tr>

        {% endfor %}

    </tbody>
</table>

backend/cmsinv/templates/cmsinv/_inventory_item_summary.html
{% load humanize %}

{% if cmsitem_obj %}
<div class="card shadow mb-2">
    <div class="card-header d-flex justify-content-between align-items-center
                text-white bg-info">
      <span>
        <i class="fad fa-prescription-bottle-alt"></i>&nbsp;CMS Inventory Item #{{ cmsitem_obj.id }}
        {% if cmsitem_obj.discontinue %}
        &nbsp;<span class="badge badge-danger">Inactive</span>
        {% endif %}
      </span>
      <span>
        <a href="{% url 'cmsinv:InventoryItemUpdate' cmsitem_obj.pk %}" class="btn btn-sm btn-secondary text-white"> Edit </a>
      </span>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-sm-2">
                Product Name
            </div>
            <div class="col-sm-5">
                {{ cmsitem_obj.product_name }}
            </div>
            <div class="col-sm-2">
                Permit No.
            </div>
            <div class="col-sm-3">
                {% if cmsitem_obj.registration_no %}
                <a 
                    href="{% url 'drugdb:DrugDetailMatch' cmsitem_obj.registration_no %}"
                    class="btn-link"
                ><i class="fad fa-file-alt"></i>&nbsp;{{ cmsitem_obj.registration_no }}
                </a>
                {% else %}-
                {% endif %}
            </div>
        </div>
        <div class="row">
            <div class="col-sm-2">
                Label Name
            </div>
            <div class="col-sm-5">
                {{ cmsitem_obj.label_name }}
            </div>
            <div class="col-sm-2">
                Clinic No.
            </div>
            <div class="col-sm-3">
                {{ cmsitem_obj.clinic_drug_no }}
            </div>
        </div>
        <div class="row">
            <div class="col-sm-2">
                Generic Name
            </div>
            <div class="col-sm-5">
                {{ cmsitem_obj.generic_name }}
            </div>
            <div class="col-sm-2">
                Stock Quantity
            </div>
            <div class="col-sm-3">
                {{ cmsitem_obj.stock_qty|floatformat }}
            </div>

        </div>
        <div class="row">
            <div class="col-sm-2">
                Alias
            </div>
            <div class="col-sm-5">
                {% if cmsitem_obj.alias %}{{ cmsitem_obj.alias }}
                {% else %}-
                {% endif %}
            </div>
            <div class="col-sm-2">
                Standard
                {% if cmsitem_obj.average_cost %}(Average){% endif %} Cost
            </div>
            <div class="col-sm-3">
                {{ cmsitem_obj.standard_cost }}
                {% if cmsitem_obj.average_cost %}
                ( {{ cmsitem_obj.average_cost }} )
                {% endif %}
            </div>
        </div>
        <div class="row">
            <div class="col-sm-2">
                Cert. Holder
            </div>
            <div class="col-sm-5">
                {{ cmsitem_obj.certificate_holder.name }}
            </div>
            <div class="col-sm-2">
                Unit Price
            </div>
            <div class="col-sm-3">
                {{ cmsitem_obj.unit_price }}
            </div>
        </div>
        <div class="row">
            <div class="col-sm-2">
                Ingredients
            </div>
            <div class="col-sm-10">
                {{ cmsitem_obj.ingredient }}
            </div>
        </div>
    </div>
</div>
{% else %}

<div class="alert alert-warning d-flex justify-content-between align-items-center" role="alert">
    No matching CMS Inventory Item
</div>

{% endif %}

backend/cmsinv/templates/cmsinv/inventory_item_quickedit_modal.html
{% load crispy_forms_tags %}

<div class="modal-header">
  <h5 class="modal-title">Quick Edit: {{ item_obj.product_name }}</h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<div class="modal-body">
  {% include 'drugdb/_regdrug_summary.html' %}
  {% if match_drug_list %}
  <div class="card">
      <div class="card-header d-flex justify-content-between align-items-center">
          No match registration number match. Possible matching registered drugs:
          <a href="#" class="btn btn-sm btn-secondary"> Push to CMS </a>
      </div>
      <div class="card-body">
        <table class="table table-sm table-striped">
          <thead>
              <tr>
                  <th scope="col">Reg No.</th>
                  <th scope="col">Product Name</th>
                  <th scope="col">Ingredients</th>
                  <th scope="col">Action</th>
              </tr>
          </thead>
          <tbody>
            {% for drug in match_drug_list %}
              <tr>
                  <td>{{ drug.reg_no }}</td>
                  <td>{{ drug.name }}</td>
                  <td>{{ drug.ingredients_list }}</td>
                  <td class="match-drug-action-cell">
                      <button
                        class="btn_quickedit_reg btn btn-link"
                        data-id="{% url 'cmsinv:InventoryItemQuickEditModal' item_obj.id %}?reg_no={{drug.reg_no}}"  
                      ><i class="fad fa-edit"></i>
                      </button>
                  </td>
              </tr>
              {% endfor %}
      
          </tbody>
        </table>
      </div>
  </div>
  {% endif %}
  <div class="card shadow mb-2">
    <div class="card-header bg-light align-items-center">
      <div class="row">
        <div class="col-2 d-flex align-items-center">
          <strong>Edit Item</strong>
        </div>
        <div class="col-10 d-flex justify-content-between">
          <div>
            <button class="btn btn_update_all btn-sm btn-secondary">Match RegDrug <i class="fad fa-arrow-circle-down"></i></button>
            {% if item_obj.discontinue %}
            <span class="badge badge-danger">Inactive/Discontinued</span>
            {% endif %}
          </div>
          <span>
            <div class="btn-group" role="group" aria-label="Reference">
              {% if item_obj.registration_no %}
              <button type="button" class="btn btn-sm btn-light" disabled>
                Reg # {{ item_obj.registration_no }}
              {% elif set_match_drug %}
              <button type="button" class="btn btn-sm btn-warning" disabled>
                Reg # None <i class="fad fa-arrow-to-right"></i> {{ drug_obj.reg_no }}
              </button>
              {% endif %}
              {% if item_obj.clinic_drug_no %}
              <button type="button" class="btn btn-sm btn-light" disabled># {{ item_obj.clinic_drug_no }}</button>
              {% endif %}
            </div>
            <div class="btn-group" role="group" aria-label="Detail Edit Actions">
              <a href="{% url 'cmsinv:InventoryItemUpdate' item_obj.pk %}" class="btn btn-sm btn-light"><i class="fad fa-edit"></i></a>
            </div>
          </span>
        </div>
        
      </div>
      
    </div>
    <div class="card-body">
      {% crispy form %}
    </div>
  </div>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
</div>

{{ drug_obj.name|json_script:"product_name" }}
{{ drug_obj.ingredients_list|json_script:"ingredients"}}
{{ generic_name|json_script:"generic_name"}}
{{ next_clinic_no|json_script:"next_clinic_no" }}
<script type="text/javascript">
  product_name = JSON.parse(document.getElementById("product_name").textContent)
  ingredients = JSON.parse(document.getElementById("ingredients").textContent)
  generic_name = JSON.parse(document.getElementById("generic_name").textContent)
  $(".btn_update_all").click(function() {
      $("#id_product_name").val(product_name)
      $("#id_label_name").val(product_name)
      $("#id_ingredient").val(ingredients)
      $("#id_generic_name").val(generic_name)
  })
  $(".btn_update_product").click(function() {
      $("#id_product_name").val(product_name)
  });
  $(".btn_update_label").click(function() {
      $("#id_label_name").val(product_name)
  });
  $(".btn_update_ingredient").click(function() {
      $("#id_ingredient").val(ingredients)
  });
  $(".btn_update_generic").click(function() {
      $("#id_generic_name").val(generic_name)
  });
  $(".btn_quickedit_reg").each(function () {
    $(this).modalForm({
        formURL: $(this).data('id')
    });
  });    
  next_clinic_no = JSON.parse(document.getElementById("next_clinic_no").textContent);
  $('#id_discontinue').on('change', function() {
    // If item set as active (discontinue set from checked -> not checked)
    if ($('#id_discontinue').is(':checked')) {
      // Set clinic drug as not checked
      $('#id_is_clinic_drug_list').prop('checked', false);
      $('#id_is_master_drug_list').prop('checked', true);
    }
    else {
      if ($('#id_clinic_drug_no').val() == '') {
        $('#id_clinic_drug_no').val(next_clinic_no)
      }
      // Set clinic drug as checked
      $('#id_is_clinic_drug_list').prop('checked', true);
    }
  });
</script>