backend/cmsacc/urls.py
from django.urls import path
from . import views

app_name = 'cmsacc'
urlpatterns = [
    path('payments/today', views.PaymentsToday.as_view(), name='PaymentToday'),
    ]

backend/cmsinv/urls.py
from django.urls import path
from . import views

app_name = 'cmsinv'
urlpatterns = [
    path('delivery/new/fromorder/<int:delivery_id>/modal/', views.NewDeliveryFromDeliveryOrderModalView, name='NewDeliveryFromDeliveryOrderModal'),
    path('suppliers/', views.SupplierList.as_view(), name='SupplierList'),
    path('supplier/<int:pk>/quickedit/modal/', views.SupplierQuickEditModal.as_view(), name='SupplierQuickEditModal'),
    # path('item/match/delivery/<int:delivery_id>/', views.MatchDeliveryInventoryItemList.as_view(), name='MatchDeliveryInventoryItemList'), # Non-CMS Delivery
    # path('item/match/<str:reg_no>/', views.MatchInventoryItemList.as_view(), name='MatchInventoryItemList'),
    # path('item/match/<int:pk>/update/', views.InventoryItemMatchUpdate.as_view(), name='InventoryItemMatchUpdate'),
    path('item/<int:pk>/quickedit/modal/', views.InventoryItemQuickEditModal.as_view(), name='InventoryItemQuickEditModal'),
    path('item/<int:pk>/update/', views.InventoryItemUpdate.as_view(), name='InventoryItemUpdate'),
    # path('item/<int:pk>/delete/', views.InventoryItemDelete.as_view(), name='InventoryItemDelete'),
    path('item/<int:pk>/', views.InventoryItemDetail.as_view(), name='InventoryItemDetail'),
    path('item/<int:pk>/modal/', views.InventoryItemDetailModal.as_view(), name='InventoryItemDetailModal'),
    path('item/new/', views.NewInventoryItem.as_view(), name='NewInventoryItem'),
    path('items/', views.InventoryItemList.as_view(), name='InventoryItemList'),
    path('movelog/', views.InventoryMovementLogList.as_view(), name='InventoryMovementLog'),
    ]

backend/cmssys/urls.py
from django.urls import path
from . import views

app_name = 'cmssys'
urlpatterns = [
    path('auditlog/', views.AuditLogList.as_view(), name='AuditLog'),
    ]

backend/config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from . import views

urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('cms-admin/', admin.site.urls),
    path('cms-auth/', include('django.contrib.auth.urls')),
    path('cmsacc/', include('cmsacc.urls')),
    path('cmsinv/', include('cmsinv.urls')),
    path('cmssys/', include('cmssys.urls')),
    path('drugdb/', include('drugdb.urls')),
    path('inventory/', include('inventory.urls')),
    path('ledger/', include('ledger.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('', views.HomeSelectVendorView, name='home'),
    # path('', TemplateView.as_view(template_name='home.html'), name='home'),
]

backend/drugdb/urls.py
from django.urls import path
from . import views

app_name = 'drugdb'
urlpatterns = [
    path('', views.RegisteredDrugList.as_view(), name='DrugList'),
    path('drug/<str:reg_no>/match/', views.DrugDetailMatch.as_view(), name='DrugDetailMatch'),
    path('drug/<str:reg_no>/link/<int:cmsitem_id>/', views.LinkCMSItemModalView, name='LinkCMSItemModal'),
]

backend/ledger/urls.py
from django.urls import path
from . import views

app_name = 'ledger'
urlpatterns = [
    path('expense/category/<int:pk>/update/', views.ExpenseCategoryUpdate.as_view(), name='ExpenseCategoryUpdate'),
    path('expense/category/', views.ExpenseCategoryList.as_view(), name='ExpenseCategoryList'),
    path('expense/export/csv/', views.ExpenseExportCsv, name='ExpenseExportCsv'),
    path('expense/<int:pk>/update/', views.ExpenseUpdate.as_view(), name='ExpenseUpdate'),
    path('expense/<int:pk>/update/modal/', views.ExpenseUpdateModal.as_view(), name='ExpenseUpdateModal'),
    path('expense/<int:pk>/delete/modal/', views.ExpenseDeleteModal.as_view(), name='ExpenseDeleteModal'),
    # path('expenses/vendor/<int:vendor_id>/new/', views.NewExpenseByVendorModal.as_view(), name='NewExpenseByVendorModal'),
    path('expense/new/modal/', views.NewExpenseModal.as_view(), name='NewExpenseModal'),
    path('expense/new/selectvendor/', views.NewExpenseSelectVendorView, name='NewExpenseSelectVendor'),
    path('expense/new/delivery/<int:delivery_id>/modal/', views.DeliveryPaymentModal.as_view(), name='DeliveryPaymentModal'),
    path('expense/new/vendor/<int:vendor_id>/', views.NewDeliveryOrderPayment.as_view(), name='NewDeliveryOrderPayment'),
    path('expense/<int:expense_id>/add/delivery/<int:delivery_id>/', views.ExpenseAddDeliveryOrder, name='ExpenseAddDeliveryOrder'),
    path('expense/<int:expense_id>/remove/delivery/<int:delivery_id>/', views.ExpenseRemoveDeliveryOrder, name='ExpenseRemoveDeliveryOrder'),
    path('expense/<int:pk>/makepermanent', views.ExpenseConfirmPermanentModalView, name="ExpenseConfirmPermanentModal"),
    path('expense/<int:expense_id>/togglepermanent', views.ExpenseTogglePermanent, name="ExpenseTogglePermanent"),
    path('expense/<int:pk>/', views.ExpenseDetail.as_view(), name='ExpenseDetail'),
    path('expense/new/', views.NewExpense.as_view(), name='NewExpense'),
    path('expense/', views.ExpenseList.as_view(), name='ExpenseList'),
    path('income/<int:pk>/delete/modal/', views.IncomeDeleteModal.as_view(), name='IncomeDeleteModal'),
    path('income/<int:pk>/update/modal/', views.IncomeUpdateModal.as_view(), name='IncomeUpdateModal'),
    path('income/<int:pk>/', views.IncomeDetail.as_view(), name='IncomeDetail'),
    path('income/new/modal', views.NewIncomeModal.as_view(), name='NewIncomeModal'),
    path('income/', views.IncomeList.as_view(), name='IncomeList'),
    ]

backend/templates/_confirm_delete_modal.html
{# % load widget_tweaks % #}

<div class="modal-header">
  <h5 class="modal-title">
    {% block title %}
    {% endblock %}
  </h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<div class="modal-body">
  {% block body %}
  {% endblock %}
</div>

<div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal">
    Cancel
  </button>
</div>

backend/templates/_datepicker_from_to.html
<div class="col-sm-4">
  <div class="form-group">
    <div class="input-group input-group-sm date" id="datepicker_from" data-target-input="nearest">
      <div class="input-group-prepend">
        <span class="input-group-text">From:</span>
      </div>
      <input type="text" 
              class="form-control form-control-sm datetimepicker-input"
              data-target="#datepicker_from"
              placeholder="YYYY-MM-DD"
              value="{{ begin }}"
              name="begin"
      >
      <div class="input-group-append" data-target="#datepicker_from" data-toggle="datetimepicker">
        <div class="input-group-text"><i class="fa fa-calendar"></i></div>
      </div>
    </div>
  </div>
</div>
<div class="col-sm-4">
  <div class="form-group">
    <div class="input-group input-group-sm date" id="datepicker_to" data-target-input="nearest">
      <div class="input-group-prepend">
        <span class="input-group-text">To:</span>
      </div>
      <input type="text" 
              class="form-control form-control-sm datetimepicker-input"
              data-target="#datepicker_to"
              placeholder="YYYY-MM-DD"
              value="{{ end }}"
              name="end"

      >
      <div class="input-group-append" data-target="#datepicker_to" data-toggle="datetimepicker">
        <div class="input-group-text"><i class="fa fa-calendar"></i></div>
      </div>
    </div>
  </div>
</div>
<div class="col-sm-4">
  <div class="btn-group btn-group-sm" role="group" aria-label="Quick Date Filter">
    <button id="btn-view_last_month" class="btn btn-light btn-outline-secondary" type="button">
      Last 1m
    </button>
    <button id="btn-view_last_3_months" class="btn btn-light btn-outline-secondary" type="button">
      3m
    </button>
    <button id="btn-view_last_6_months" class="btn btn-light btn-outline-secondary" type="button">
      6m
    </button>    
    <button id="btn-view_all" class="btn btn-light btn-outline-secondary" type="button">
      Any
    </button>
  </div>
</div>

      
  

backend/templates/_footer.html
<footer class="bg-white sticky-footer">
  <!-- <div class="container my-auto">
    <div class="text-center my-auto copyright">
      <span>Copyright © cmsMan 2020</span>
    </div>
  </div> -->
</footer>

backend/templates/_header.html
{% load static %}

<!-- Header -->
<header>
    <nav class="navbar navbar-expand-sm navbar-dark cmm-masthead">
        <a class="navbar-brand" href="{% url 'home' %}"><i class="fad fa-laptop-medical"></i></a>
        <button class="navbar-toggler mr-auto" type="button" data-toggle="collapse" data-target="#navbarBaseToggler"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class= "collapse navbar-collapse" id="navbarBaseToggler">
            <ul class="navbar-nav mr-auto mt-2 mt-sm-0">
                {% if user.is_staff and perms.ledger.add_expense %}
                <li class="nav-item">
                    <a href="{% url 'ledger:NewExpense' %}" class="nav-link">+<i class="far fa-file-invoice-dollar"></i></a>
                </li>
                {% endif %}

                {% if perms.ledger.view_expense %}
                <li class="nav-item">
                    <a href="{% url 'ledger:ExpenseList' %}" class="nav-link">Expenses</a>
                </li>
                {% endif %}
                {% if perms.ledger.view_income %}
                <li class="nav-item">
                    <a href="{% url 'ledger:IncomeList' %}" class="nav-link">Income</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a href="{% url 'inventory:DeliveryOrderList' %}" class="nav-link">Deliveries</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'inventory:DeliveryItemList' %}" class="nav-link">Delivered Items</a>
                </li>
                {% if perms.cmsinv.view_inventoryitem %}
                <li class="nav-item">
                    <a href="{% url 'cmsinv:InventoryItemList' %}" class="nav-link">CMS Inventory</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a href="{% url 'drugdb:DrugList' %}" class="nav-link">Reg Drugs</a>
                </li>
                {% if perms.cmsacc.view_paymentdetails %}
                <li class="nav-item">
                    <a href="{% url 'cmsacc:PaymentToday' %}" class="nav-link">Payments</a>
                </li>
                {% endif %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="{% url 'cmsinv:InventoryItemList' %}"
                        id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fad fa-tags"></i>
                    </a>
                    <div class="dropdown-menu">
                        <a href="{% url 'inventory:Stocktake' %}" class="dropdown-item">Stocktake</a>
                        <a href="{% url 'inventory:ItemList' %}" class="dropdown-item">Item List</a>
                        <a href="{% url 'inventory:VendorList' %}" class="dropdown-item">Vendor List</a>
                        {% if perms.cmsinv.view_auditlog %}
                        <a href="{% url 'cmsinv:SupplierList' %}" class="dropdown-item">
                            CMS Supplier Manufacturer List
                        </a>
                        <a href="{% url 'cmsinv:InventoryMovementLog' %}" class="dropdown-item">
                            CMS Inventory Movement Log
                        </a>
                        <a href="{% url 'cmssys:AuditLog' %}" class="dropdown-item">
                            CMS Audit Log
                        </a>
                        {% endif %}
                    </div>
                </li>
            </ul>
            <ul class="navbar-nav my-2 my-sm-0">
                {% if user.is_staff %}
                <li class="nav-item">
                    <a href="{% url 'admin:index' %}" class="nav-link">[{{ user.username }}]</a>
                </li>
                {% else %}
                <span class="navbar-text">[{{ user.username }}]</span>
                {% endif %}
                <li class="nav-item">
                    <a href="{% url 'logout' %}" class="nav-link">Logout</a>
                </li>
            </ul>
        </div>
    </nav>
</header>

backend/templates/_modal.html
<!-- <div
  class="modal fade"
  id="create-modal"
  tabindex="-1"
  role="dialog"
  aria-hidden="true"
>
  <div class="modal-dialog modal-xl">
    <div class="modal-content"></div>
  </div>
</div> -->

<div class="modal fade" tabindex="-1" role="dialog" id="modal">
  <div class="modal-dialog modal-dialog-centered modal-xl" role="document">
    <div class="modal-content"></div>
  </div>
</div>

backend/templates/base.html
{% load static %}
{# Load the tag library #}
{#% load bootstrap4 %#}

{# Load CSS and JavaScript #}
{#  {% bootstrap_css %} #}
{#  {% bootstrap_javascript jquery='full' %} #}


<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  {% block stylesheets %}
  <link rel="shortcut icon" type="image/png" href="{% static '/assets/favicon.ico' %}"/>
  <script src="{% static '/assets/js/jquery.min.js' %}"></script>
  <!-- Bootstrap CSS -->
  <link href="{% static '/assets/bootstrap/css/bootstrap.css' %}" rel="stylesheet"/>
  <!-- Font awesome CSS -->
  <link href="{% static '/assets/css/all.css' %}" rel="stylesheet"/>
  <!-- Custom CSS-->
  <link href="{% static '/assets/css/cmsman.css' %}" rel="stylesheet"/>
  <link href="{% static '/assets/css/tempusdominus-bootstrap-4.min.css' %}" rel="stylesheet"/>

  <title>
    {% block title %}CMS Manager{% endblock %}
  </title>
  {% endblock stylesheets %}
</head>

<body id="page-top">
  <div id="wrapper">
    {% if user.is_authenticated %}

    <!-- Includes -->
    {% include "_header.html" %}

    <div class="container-fluid">
      {% block content %}
      
      <div class="row">
        <div class="col-sm-10">
          {% block main %}{% endblock main %}
        </div>
        <div class="col-sm-2">
          {% block sidebar %}{% endblock sidebar %}
        </div>
      </div>
      {% endblock content %}
      {% include "_footer.html" %}
    </div>

    {% else %}
    <div class="container mt-4">
      <div class="alert alert-danger" role="alert">
        You are not logged in. <a class="alert-link" href="{% url 'login' %}">Click here to Login</a>
      </div>
    </div>
    {% endif %}
    </div>
  <!-- Javascript -->
  {% block scripts %}
  <script src="{% static '/js/jquery.bootstrap.modal.forms.min.js' %}"></script>
  <script src="{% static '/assets/bootstrap/js/bootstrap.bundle.js' %}"></script>
  <script src="{% static '/assets/js/moment.js' %}"></script>
  <script src="{% static '/assets/js/popper.min.js' %}"></script>
  <script src="{% static '/assets/js/tempusdominus-bootstrap-4.min.js' %}"></script>
  {% endblock scripts %}

  {% block extrascripts %}{% endblock extrascripts %}
</body>

</html>

backend/templates/home.html
{% extends 'base.html' %} 

{% block content %}

{% include "_modal.html" %}

<div class="card shadow">
    <div class="card-header bg-dark text-white">
        Add Delivery Order / Expense
    </div>
    <div class="card-body">
      <p>Search for vendor/supplier then click on icon for adding delivery order / expense:</p>
      <div class="row">
        <div class="col-sm-10">
          <div class="input-group input-group-sm mb-2">
            <div class="input-group-prepend">
                <span class="input-group-text" id="search-icon">
                    <i class="far fa-search"></i> </span>
            </div>
            <input class="form-control" id="user-input" placeholder="Search by name or alias" size="50">
        </div>
      </div>
      <div class="col-sm-2">
        <a href="{% url 'inventory:NewVendor' %}?next={{ request.path }}" id="btn_new_vendor" class="btn btn-sm btn-success btn-block"
          >New Vendor 
        </a>
      </div>
    </div>
      
      <div id="search-results">               
          {% include 'inventory/_choose_vendor.html' %}
      </div>
    </div>
</div>

{% endblock %}

{% block extrascripts %}

<script type="text/javascript">
    $(document).ready(function () {
        
        const user_input = $("#user-input")
        const search_icon = $('#search-icon')
        const results_div = $('#search-results')
        const endpoint = ''
        const delay_by_in_ms = 300
        let scheduled_function = false

        let ajax_call = function (endpoint, request_parameters) {
            $.getJSON(endpoint, request_parameters)
                .done(response => {
                        // fade-out, then display contents:
                        results_div.fadeTo('fast', 0).promise().then(() => {
                        results_div.html(response['html_from_view'])
                        // fade-in with new contents
                        results_div.fadeTo('fast', 1)
                        $(".btn_modal_trigger").each(function() {
                            $(this).modalForm({
                                formURL: $(this).data('id')
                                })
                            })
                        })
                })
        }
        // Check for input on document load and execute ajax if not empty
        query = user_input.val()
        console.log('Search input:', query)
        if (query) {
            const request_parameters = {
                q: query,
                next: location.pathname,
            }
            ajax_call(endpoint, request_parameters)
        }

        user_input.on('keyup', function () {
            const request_parameters = {
                q: $(this).val(), // value of user_input: the HTML element with ID user-input
                vendor: '',
                next: location.pathname,
            }

            // if scheduled_function is NOT false, cancel the execution of the function
            if (scheduled_function) {
                clearTimeout(scheduled_function)
            }

        // setTimeout returns the ID of the function to be executed
            scheduled_function = setTimeout(ajax_call, delay_by_in_ms, endpoint, request_parameters)
        })
        $(".btn_modal_trigger").each(function() {
            $(this).modalForm({
                formURL: $(this).data('id')
                })
            });
        $("#user-input").focus()
    })
</script>
{% endblock %}